services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis-net
    depends_on:
      - mysql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  redis-net:
  zipkin:
  mysql:
    driver: bridge
