spring:
  application:
    name: spring-data-redis-cache.
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto=update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    username: user
    password: pass
    database: 0
    timeout: 10000 # Timeout in milliseconds
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  cache:
    type: redis
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9696

