spring:
  application:
    name: spring-data-redis-cache.
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  zipkin:
    base-url: http://localhost:9411
  data:
    redis:
      host: localhost
      port: 6379
      password: redispass
      database: 0
      timeout: 10000
      username: redisuser
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
server:
  port: 9696

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
